# Generated by Django 5.2.4 on 2025-08-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.libro'),
        ),
    ]
